<?php echo $this->doctype() ?>
<html>
    <head>    
        <?php echo $this->headTitle(); ?> 
        <?php echo $this->headMeta(); ?> 
        <?php echo $this->headLink(); ?> 
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?> 
        <?php echo $this->inlineScript(); ?>
		
    </head>

    <body>
        <div style="width: 100%; margin: 0px;">
          
             <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
               
               
            </div>
        </nav>
        
        <div class="form">
     
        
        <div id="login">   
         <br><br><br>
          
          <div class="notification">
	<?php
		//if(!empty($this->message)){
            echo $this->message[0];
           // print_r($this->resultrow);
		//}?>
    
   

    </div>
          <center>
          
        <a href="/index/sendotp/id/iphone"> <img src="<?php echo SITE_URL."/upload/Apple-logo.jpg"?>" width="200px;" height="200px"></a>
		 <a href="/index/sendotp/id/android"><img src="<?php echo SITE_URL."/upload/android_vector.jpg"?>" width="200px;" height="200px"></a>
		  </center>
        </div>
        
		<br><br><br><br><br><br><br><br>
      </div><!-- tab-content -->
      
   
            
            <?php // echo $this->layout()->content; ?>
            
        </div>
    </body>

</html>