<?php echo $this->doctype();?>
<html>
    <head>    
        <?php echo $this->headTitle(); ?> 
        <?php echo $this->headMeta(); ?> 
        <?php echo $this->headLink(); ?> 
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?> 
        <?php echo $this->inlineScript(); ?>
		<script src="https://www.google.com/recaptcha/api.js" async defer></script>
    </head>

    <body>
        <div style="width: 100%; margin: 0px;">
          
             <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
               
               
            </div>
        </nav>
        
        <div class="form">
     
        
        <div id="login">   
         
          <center>
			
          <div class="notification">
	
	<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');
	 if ($flashMessenger->hasMessages('success')): ?>
    <div class="message success" >
    <?php foreach ($flashMessenger->getMessages('success') as $msg): ?>
        <?php echo $msg ?>
    <?php endforeach; ?>
    </div>
<?php endif; ?>

    </div>
		  </center>
		  <br>
				  		 
          <center>
          
       <div class='container'>
    <form method="post" action="/index/sendmsg">
        <div class='form_ele'>
            <div class='left'>
                <label>Please Enter CTN :</label>
            </div>
            <div class='right'>
                <input type="text" name="ctn"/>
				<input type="hidden" name="type" value="<?php echo $this->sendotp['id']; ?>">
				<input type="hidden" name="link" value="<?php echo $this->sendotp['link']; ?>">
            </div>
        </div>
        <div class='form_ele'>
            <div class='left'>
                <label>Please Enter Email :</label>
            </div>
            <div class='right'>
                <input type="email" name="email"/>
            </div>
        </div>
        <div class='form_ele'>
            <div class='left'>
                <label>IMEI *#08# :</label>
            </div>
            <div class='right'>
                <input type="text" name="imei"/>
            </div>
        </div>
		
				<div class="notification">
				
				<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');
				if ($flashMessenger->hasMessages('error')): ?>
				<div class="message success" >
				<?php foreach ($flashMessenger->getMessages('error') as $msg): ?>
				<?php echo $msg ?>
				<?php endforeach; ?>
				</div>
				<?php endif; ?>
				
				</div>
<br><br>
		 <div class="g-recaptcha" data-sitekey="6LeRFh0TAAAAAGnj4JLLWHPb_UuYhdgfEsoD19wj"></div>
        
        <div class='form_ele'>
            <div class='left'>
                &nbsp;
            </div>
            <div class='right'>
                <input type="submit" name="submit" value="Send" class='btn'/>
               
            </div>
        </div>
    </form>
</div>
		  </center>
        </div>
        
      </div><!-- tab-content -->
      
   
            
            <?php // echo $this->layout()->content; ?>
            
        </div>
    </body>
	  <br><br><br><br>
</html>