<style>
    .container{width: 1000px; margin: 0 auto; border: #ccc solid 1px; min-height: 250px; margin-top: 15px;}
    .form_ele{width: 100%; margin: 10px 0px; clear: both;}
    .form_ele .left{width: 350px; float: left; text-align: right; padding-top: 5px;}
    .form_ele .left label{margin-right: 15px;}
    input[type=text],input[type=password]{width: 250px; height: 25px; border: #ccc solid 1px; padding-left: 5px;}
    .btn{background-color: #005FA0; border: 0 none; border-radius: 3px 3px 3px 3px; color: #FFFFFF; height: 33px; padding-bottom: 5px; width: 100px;}
</style>
<div class='container'>
 
 
			<h3> <u> <center> Manage Email Credentials </center> </u> </h3>
    <div class="notification">
	<?php
		if(!empty($this->message)){?>
            <?php echo $this->message[0]; 
			}
			//print_r($this->resultrow);
			//echo "test".UPLOAD_DIRECTORY;
			
			?>
    

    </div>    
 
 
 
    <form method="post" name="frm_reg" action="/index/updateemail">
        <div class='form_ele'>
            <div class='left'>
                <label>Email Username :</label>
            </div>
            <div class='right'>
                <input type="text" value="<?php echo $this->resultrow[0]->email_username;?>" name="info[email_username]"/>
            </div>
        </div>
        <div class='form_ele'>
            <div class='left'>
                <label>Email Password :</label>
            </div>
            <div class='right'>
                <input type="text" value="<?php echo $this->resultrow[0]->email_password;?>" name="info[email_password]"/>
            </div>
        </div>
        
        <div class='form_ele'>
            <div class='left'>
                <label>Send From :</label>
            </div>
            <div class='right'>
                <input type="text" value="<?php echo $this->resultrow[0]->send_from;?>" name="info[send_from]"/>
            </div>
        </div>
		
		    <div class='form_ele'>
            <div class='left'>
                <label>Email Body :</label>
            </div>
            <div class='right'>
                <textarea name="info[email_body]" style="width:350px; height:80px;" cols="42" rows="5">
					<?php echo $this->resultrow[0]->email_body;?>
				</textarea>
            </div>
        </div>
        
        <div class='form_ele'>
            <div class='left'>
                &nbsp;
            </div>
            <div class='right'>
                <input type="submit" name="submit" value="Submit" class='btn'/>
                
            </div>
        </div>
    </form>
</div>