<?php echo $this->doctype() ?>
<html>
    <head>    
        <?php echo $this->headTitle(); ?> 
        <?php echo $this->headMeta(); ?> 
        <?php echo $this->headLink(); ?> 
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?> 
        <?php echo $this->inlineScript(); ?>  
    </head>
  <section class="main-content">
	<br>
   <center>
			
	<?php
		if(!empty($this->data)){
			
           // print_r($this->data);
           // print_r($this->resultrow);
		   if($this->data['type']=="iphone"){
		   ?>
		   <h3> <?php echo $this->data['step_1_above_text'] ?> </h3>
		   
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_image1']?>">
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_image2']?>">
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_image3']?>">
		   <br><br>
		   <h3> <?php echo $this->data['step_1_below_text'] ?> </h3>
		   <br><br>
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_1_image1']?>">
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_1_image2']?>">
		   <?php }
		   if($this->data['type']=="android"){ ?>
			
			<br><br>
			  <h3> <?php echo $this->data['step_2_above_text'] ?> </h3>
		   <br><br>
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_a_image1']?>">
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_a_image2']?>">
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_a_image3']?>">
		   <br><br>
		   <h3> <?php echo $this->data['step_2_below_text'] ?> </h3>
		   <br><br>
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_1_a_image1']?>">
		   <img src="<?php echo SITE_URL."/upload/".$this->data['step_3_1_a_image2']?>">
		  
			<?php }?>
		
	
	<?php }?>
          </center>
  </section>
  