<?php echo $this->doctype() ?>
<html>

  <section class="main-content">
	   <h1></h1>
	    <center>
			<h4><?php echo $this->resultrow[0]->above_text; ?></h4>
 
        <a href="/index/sendotp/id/iphone"> <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->image_1?>" width="200px;" height="200px"></a>
		 <a href="/index/sendotp/id/android"><img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->image_2?>" width="200px;" height="200px"></a>
		 
		 	<h4><?php echo $this->resultrow[0]->below_text; ?></h4>
		  </center>
	
  </section>