<?php echo $this->doctype() ?>
<html>
    <head>    
        <?php echo $this->headTitle(); ?> 
        <?php echo $this->headMeta(); ?> 
        <?php echo $this->headLink(); ?> 
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?> 
        <?php echo $this->inlineScript(); ?>  
    </head>

    <body>
        <div style="width: 100%; margin: 0px;">
          
             <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
            </div>
        </nav>
        
        <div class="form">
     
        
        <div id="login">   
         
		  
          <div class="notification">
	<?php
		//if(!empty($this->message)){
            echo $this->message[0];
           // print_r($this->resultrow);
		//}?>
     </div>
          
          <center><h3> <a href="/index/index"> Home </a>||<a href="/index/choosedevice"> Step 1 </a>|| &nbsp;&nbsp;&nbsp;<a href="/index/fronthand"> Step 2 </a>  || &nbsp;&nbsp;&nbsp;<a href="/index/index1">Step 3 </a>   </h3>
		  </center>
       

        </div>
        
      </div>
           
           <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br> 
        </div>
    </body>

</html>