<section class="main-content">
<h1></h1>
	  <div class="notification">
	<?php
		//if(!empty($this->message)){
            echo $this->message[0];
           // print_r($this->resultrow);
		//}?>
     </div>
	  
   <form action="/index/add" method="post" enctype="multipart/form-data">
          <h3>Step 3 Iphone</h3>
            <div class="field-wrap">
            <label>
             Above Logo Text<span class="req">*</span>
            </label>
            <textarea name="info[step_1_above_text]" style="width:350px; height:80px;" cols="42" rows="5"><?php echo $this->resultrow[0]->step_1_above_text;?></textarea>

          </div>
			
			
			 <div class="field-wrap">
            <label>
              Image 1<span class="req">*</span>
            </label>
            <?php
            if(!empty($this->resultrow[0]->step_3_image1)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_image1 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_image1" />
            
          </div>
            
            
            <div class="field-wrap">
            <label>
              Image 2<span class="req">*</span>
            </label>
             <?php
            if(!empty($this->resultrow[0]->step_3_image2)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_image2 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_image2"/>
          </div>
			
            <div class="field-wrap">
            <label>
              Image 3<span class="req">*</span>
            </label>
              <?php
            if(!empty($this->resultrow[0]->step_3_image3)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_image3 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_image3"/>
          </div>
			
			
            
            
            <div class="field-wrap">
            <label>
             Below Logo Text<span class="req">*</span>
            </label>
            <textarea name="info[step_1_below_text]" style="width:350px; height:80px;" cols="42" rows="5"><?php echo $this->resultrow[0]->step_1_below_text; ?></textarea>
            
          </div>
			
			
			<div class="field-wrap">
            <label>
              Image 1<span class="req">*</span>
            </label>
             <?php
            if(!empty($this->resultrow[0]->step_3_1_image1)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_1_image1 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_1_image1"/>
          </div>
            
            
            <div class="field-wrap">
            <label>
              Image 2<span class="req">*</span>
            </label>
              <?php
            if(!empty($this->resultrow[0]->step_3_1_image2)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_1_image2 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_1_image2"/>
          </div>
                        
						
					<!---  For Android -->
					
					
					
            
            
            
             <h3>Step 3.1 For Android</h3>
            <div class="field-wrap">
            <label>
             Above Logo Text<span class="req">*</span>
            </label>
            
             <textarea name="info[step_2_above_text]" style="width:350px; height:80px;" cols="42" rows="5"><?php echo $this->resultrow[0]->step_2_above_text; ?></textarea>
          </div>
			
			
			 <div class="field-wrap">
            <label>
              Image 1<span class="req">*</span>
            </label>
            <?php
            if(!empty($this->resultrow[0]->step_3_a_image1)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_a_image1 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_a_image1" />
            
          </div>
            
            
            <div class="field-wrap">
            <label>
              Image 2<span class="req">*</span>
            </label>
             <?php
            if(!empty($this->resultrow[0]->step_3_a_image2)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_a_image2 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_a_image2"/>
          </div>
			
            <div class="field-wrap">
            <label>
              Image 3<span class="req">*</span>
            </label>
              <?php
            if(!empty($this->resultrow[0]->step_3_a_image3)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_a_image3 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_a_image3"/>
          </div>
			
			            
            <div class="field-wrap">
            <label>
             Below Logo Text<span class="req">*</span>
            </label>
            <textarea name="info[step_2_below_text]" style="width:350px; height:80px;" cols="42" rows="5"><?php echo $this->resultrow[0]->step_2_below_text; ?></textarea>
           
          </div>
			
			<div class="field-wrap">
            <label>
              Image 1<span class="req">*</span>
            </label>
             <?php
            if(!empty($this->resultrow[0]->step_3_1_a_image1)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_1_a_image1 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_1_a_image1"/>
          </div>
            
            
            <div class="field-wrap">
            <label>
              Image 2<span class="req">*</span>
            </label>
              <?php
            if(!empty($this->resultrow[0]->step_3_1_a_image2)){?>
            <img src="<?php echo SITE_URL."/upload/".$this->resultrow[0]->step_3_1_a_image2 ?>" width="100px;" height="100px;">
            <?php } ?>
            <input type="file" name="step_3_1_a_image2"/>
          </div>
			
			<!--  closed-->
			
            
                     <button class="button button-block"/>Submit</button>
          
          </form>
  </section>
