<style>
    .container{width: 1000px; margin: 0 auto; border: #ccc solid 1px; min-height: 250px; margin-top: 15px;}
    .form_ele{width: 100%; margin: 10px 0px; clear: both;}
    .form_ele .left{width: 350px; float: left; text-align: right; padding-top: 5px;}
    .form_ele .left label{margin-right: 15px;}
    input[type=text],input[type=password]{width: 250px; height: 25px; border: #ccc solid 1px; padding-left: 5px;}
    .btn{background-color: #005FA0; border: 0 none; border-radius: 3px 3px 3px 3px; color: #FFFFFF; height: 33px; padding-bottom: 5px; width: 100px;}
</style>
<div class='container'>
    <form method="post" name="frm_reg">
        <div class='form_ele'>
            <div class='left'>
                <label>Name :</label>
            </div>
            <div class='right'>
                <input type="text" name="name"/>
            </div>
        </div>
        <div class='form_ele'>
            <div class='left'>
                <label>Email :</label>
            </div>
            <div class='right'>
                <input type="text" name="email"/>
            </div>
        </div>
        <div class='form_ele'>
            <div class='left'>
                <label>Password :</label>
            </div>
            <div class='right'>
                <input type="password" name="password"/>
            </div>
        </div>
        <div class='form_ele'>
            <div class='left'>
                <label>Mobile :</label>
            </div>
            <div class='right'>
                <input type="text" name="mobile"/>
            </div>
        </div>
        <div class='form_ele'>
            <div class='left'>
                <label>Gender :</label>
            </div>
            <div class='right'>
                <input type="radio" name="gender" value='Male'/>Male
                <input type="radio" name="gender" value='Female'/>Female
            </div>
        </div>
        <div class='form_ele'>
            <div class='left'>
                &nbsp;
            </div>
            <div class='right'>
                <input type="submit" name="submit" value="Register" class='btn'/>
                <input type="reset" name="reset" value="Clear" class='btn'/>
            </div>
        </div>
    </form>
</div>