
 <table id="keywords" cellspacing="0" cellpadding="0">
    <thead>
      <tr>
		<th><span>Start-time</span></th>
 	    <th><span>Start-date</span></th>
		<th><span>End-time</span></th>
		<th><span>End-date</span></th>
		<th><span>Imei</span></th>
		<th><span>Make</span></th>
		<th><span>Model</span></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="lalign">12.30</td>
        <td>12-06-2016</td>
        <td>12.40</td>
        <td>13-06-2016</td>
        <td>123456789256</td>
		 <td>Test</td>
		  <td>Nokia</td>
		   <td class="viewcls">Email</td>
		    <td class="viewcls">View</td>
      </tr>
	   <tr>
        <td class="lalign">12.30</td>
        <td>12-06-2016</td>
        <td>12.40</td>
        <td>13-06-2016</td>
        <td>123456789256</td>
		 <td>Test</td>
		  <td>Nokia</td>
		   <td class="viewcls">Email</td>
		    <td class="viewcls">View</td>
      </tr>
     
    
    </tbody>
  </table>
 
 
		
		<style>



table { border-collapse: collapse; border-spacing: 0; }
img { border: 0; max-width: 100%; }

h1 { 
  font-family: 'Amarante', Tahoma, sans-serif;
  font-weight: bold;
  font-size: 3.6em;
  line-height: 1.7em;
  margin-bottom: 10px;
  text-align: center;
}


/** page structure **/
#wrapper {
  display: block;
  width: 850px;
  background: #fff;
  margin: 0 auto;
  padding: 10px 17px;
  -webkit-box-shadow: 2px 2px 3px -1px rgba(0,0,0,0.35);
}

#keywords {
  margin: 0 auto;
  margin-bottom: 15px;
}
.viewcls{
  border: 2px double;
  cursor: pointer;
}


#keywords thead {
  cursor: pointer;
  background: #FFC878;
}
#keywords thead tr th { 
  padding: 8px 24px 0 32px;
}
#keywords thead tr th span { 
  padding-right: 20px;
  background-repeat: no-repeat;
  background-position: 100% 100%;
}

#keywords thead tr th.headerSortUp, #keywords thead tr th.headerSortDown {
  background: #acc8dd;
}


#keywords tbody tr { 
  color: #555;
}
#keywords tbody tr td {
  text-align: center;
  padding: 9px 5px;
}
#keywords tbody tr td.lalign {
  text-align: left;
}
		</style>