<?php echo $this->doctype() ?>
<html>

    <body>
        <div style="width: 100%; margin: 0px;">
          
             <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
               
               
            </div>
        </nav>
        
        <div class="form">
     
        
        <div id="login">   
          <h1>Welcome To BackEnd</h1>
          
          <div class="notification">
	<?php
		if(!empty($this->message)){
            echo $this->message[0]; 
		}
		
	///	print_r($this->listing);die;
		?>
    

    </div>
          
        <table cellpadding="2" cellspacing="2" border="1">
			<tr>
				<th>step_1_above_text</th>
				<th>step_1_below_text</th>
				<th>step_2_above_text</th>
				 	<th>step_2_below_text</th>
					<th>step_3_above_text</th>
					<th>step_3_image1</th>
					<th>step_3_image2</th>
					<th>step_3_image3</th>
					<th>step_3_below_text</th>
					<th>step_3_1_above_text</th>
					<th>step_3_1_image1</th>
					<th>step_3_1_image2</th>
					<th>step_3_1_below_text</th>
			</tr>
			<?php foreach($this->listing as $data){ ?>
			<tr>
				<td><?php echo $data->step_1_above_text;?></td>
				<td><?php echo $data->step_1_below_text;?></td>
				<td><?php echo $data->step_2_above_text;?></td>
				<td><?php echo $data->step_2_below_text;?></td>
				<td><?php echo $data->step_3_above_text;?></td>
				<td><?php echo $data->step_3_image1;?></td>
				<td><?php echo $data->step_3_image2;?></td>
				<td><?php echo $data->step_3_image3;?></td>
				<td><?php echo $data->step_3_below_text;?></td>
				<td><?php echo $data->step_3_1_above_text;?></td>
				<td><?php echo $data->step_3_1_image1;?></td>
				<td><?php echo $data->step_3_1_image2;?></td>
				<td><?php echo $data->step_3_1_below_text;?></td>
			</tr>
			<?php } ?>
		</table>
            
            <?php // echo $this->layout()->content; ?>
            
        </div>
    </body>

</html>