

<div class='container'>
          
          <div class="notification">
	<?php
		if(!empty($this->message)){
            echo $this->message[0]; 
		} ?>
    

    </div>
          
        <table cellpadding="2" cellspacing="2" border="1">
			<tr>
				<th>Sr.No.</th>
				<th>Contact Number</th>
				<th>Email-id</th>
				<th>IMEI</th>
				 	<th>Type</th>
					<th>OTP Number</th>
					<th>OTP Created Date</th>
					<th>status</th>
					
			</tr>
			<?php $i=1; foreach($this->resultrow as $data){
				
				if($data->status==0){ $status="Pending"; }elseif($data->status==1){ $status="Validated"; } elseif($data->status==2){ $status="Expire";}?>
			<tr>
				<td><?php echo $i;?></td>
				<td><?php echo $data->ctn;?></td>
				<td><?php echo $data->email;?></td>
				<td><?php echo $data->imei;?></td>
				<td><?php echo $data->type;?></td>
				<td><?php echo $data->otp_number;?></td>
				<td><?php echo $data->otp_send_time;?></td>
				<td><?php echo $status;?></td>
				
			</tr>
			
			<?php $i++; } ?>
		</table>
        </div>
	</center>
  </section>
