<?php echo $this->doctype() ?>
<html>
    <head>    
        <?php echo $this->headTitle(); ?> 
        <?php echo $this->headMeta(); ?> 
        <?php echo $this->headLink(); ?> 
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?> 
        <?php echo $this->inlineScript(); ?>
        <?php
       
//	$this->headLink(array('rel' => 'icon', 'href' => '/img/favicon.ico'), 'PREPEND')
//        ->appendStylesheet(SCRIPT_DIRECTORY.'/style.css');
        

// rendering the links from the layout:
echo $this->headLink();?>
    </head>

    <body>
       
            <?php echo $this->render('section/header.phtml'); ?>
            <?php echo $this->layout()->content; ?>
            <?php echo $this->render('section/footer.phtml'); ?>
    </body>

</html>